/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_sistema_sismico;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class PanelClasificacionMagnitud extends javax.swing.JPanel {

    /**
     * Creates new form PanelClasificacionMagnitud
     */
    DefaultTableModel md;
    int lenLista=0;
    Registro_sismos listaG = Registro_Singleton.getRegistro_Singleton();
    public PanelClasificacionMagnitud() throws IOException, FileNotFoundException, ParseException{
        initComponents();
        md = new DefaultTableModel();
        md = (DefaultTableModel) tbl.getModel();
        lenLista = listaG.cargar().size();
        llenarTabla();
        tbl.getTableHeader().setReorderingAllowed(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setBackground(new java.awt.Color(86, 86, 100));

        jPanel1.setBackground(new java.awt.Color(86, 86, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sismos Clasificados por nivel de Magnitud");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clasificación", "Magnitud", "Fecha", "Origen", "Latitud", "Longitud", "Provincia", "Detalle"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
private void llenarTabla()throws IOException, FileNotFoundException, ParseException{
    /*
        Funcion: Llenar la tabla con la nueva clasificación por rangos
        Entradas: Ninguna
        Salidas: Ninguna
     */
            for (int i = 0; i < lenLista; i++){
            float mag=listaG.lista.get(i).getMagnitud();
            String clasificacion="";
            if(mag<2){
                clasificacion = "Micro";
            }
            else if(mag>=2 && mag<4){
                clasificacion = "Menor";
            }
            else if(mag>=4 && mag<5){
                clasificacion = "Ligero";
            }
            else if(mag>=5 && mag<6){
                clasificacion = "Moderado";
            }
            else if(mag>=6 && mag<7){
                clasificacion = "Fuerte";
            }
            else if(mag>=7 && mag<8){
                clasificacion = "Mayor";
            }
            else if(mag>=8 && mag<10){
                clasificacion = "Gran";
            }
            else if(mag>=10){
                clasificacion = "Épico";
            }
            md.addRow(new Object[]{clasificacion,String.valueOf(listaG.lista.get(i).getMagnitud()),FormatosUtilitaria.formatoFecha(listaG.lista.get(i).getFecha()),listaG.lista.get(i).getOrigen().toString(), 
                 String.valueOf(listaG.lista.get(i).getLatitud()),String.valueOf(listaG.lista.get(i).getLongitud()),listaG.lista.get(i).getProvincia().toString(),listaG.lista.get(i).getDetalle()});
            tbl.setModel(md);
        }  
}

                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
