package proyecto1_sistema_sismico;


import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 * @author Allison
 */
public class PanelMesEnAnnio extends javax.swing.JPanel {
    Registro_sismos listaG = Registro_Singleton.getRegistro_Singleton();
    ChartPanel contenedor;
    public PanelMesEnAnnio() throws IOException, FileNotFoundException, ParseException {
        initComponents();
        agregarGrafica(0);
    }
    public void agregarGrafica(int pannio){
        int [] array = listaG.cant_sismos_mesEnAnnio_lista(pannio);
        contenedor = cant_sismos_mesEnAnnio(array);
        //contenedor.setSize(900,this.getHeight());
        contenedor.setVisible(true);
        
        
        jPanelGrafica.add(contenedor);
        contenedor.repaint();
        jPanelGrafica.revalidate();
        jPanelGrafica.repaint();
        
    }
    public ChartPanel cant_sismos_mesEnAnnio(int []parray){
        /*
        Funcion: 
        Entradas: 
        Salidas: 
        */
        DefaultCategoryDataset data = new DefaultCategoryDataset();
        data.addValue(parray[0], "Sismos en", "Enero");
        data.addValue(parray[1], "Sismos", "Febrero");
        data.addValue(parray[2], "Sismos", "Marzo");
        data.addValue(parray[3], "Sismos", "Abril");
        data.addValue(parray[4], "Sismos", "Mayo");
        data.addValue(parray[5], "Sismos", "Junio");
        data.addValue(parray[6], "Sismos", "Julio");
        data.addValue(parray[7], "Sismos", "Agosto");
        data.addValue(parray[8], "Sismos", "Septiembre");
        data.addValue(parray[9], "Sismos", "Octubre");
        data.addValue(parray[10], "Sismos", "Noviembre");
        data.addValue(parray[11], "Sismos", "Diciembre");
        
        
        
        //Se crea la grafica de BARRAS pasandole los datos
        JFreeChart grafica = ChartFactory.createBarChart("Sismos", "Meses", "Cantidad de sismos", data, PlotOrientation.VERTICAL, false, true, false);
        
        //Panel de la grafica
        ChartPanel chartpanel = new ChartPanel(grafica);
        return chartpanel;
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEntrada = new javax.swing.JPanel();
        JLannioGrafica = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        SpinBoxAnnio = new javax.swing.JSpinner();
        jPanelGrafica = new javax.swing.JPanel();

        setBackground(new java.awt.Color(86, 86, 100));
        setMaximumSize(new java.awt.Dimension(1500, 900));
        setMinimumSize(new java.awt.Dimension(900, 800));
        setPreferredSize(new java.awt.Dimension(900, 300));

        jPanelEntrada.setBackground(new java.awt.Color(86, 86, 100));
        jPanelEntrada.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanelEntrada.setLayout(null);

        JLannioGrafica.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        JLannioGrafica.setForeground(new java.awt.Color(255, 255, 255));
        JLannioGrafica.setText("Seleccione el año: ");
        jPanelEntrada.add(JLannioGrafica);
        JLannioGrafica.setBounds(0, 0, 240, 50);

        jButton1.setBackground(new java.awt.Color(86, 86, 100));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Graficar");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelEntrada.add(jButton1);
        jButton1.setBounds(390, 10, 110, 40);

        SpinBoxAnnio.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        SpinBoxAnnio.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));
        SpinBoxAnnio.setPreferredSize(new java.awt.Dimension(10, 26));
        SpinBoxAnnio.setValue(SpinBoxAnnio.getValue());
        jPanelEntrada.add(SpinBoxAnnio);
        SpinBoxAnnio.setBounds(220, 10, 160, 40);

        jPanelGrafica.setBackground(new java.awt.Color(86, 86, 100));
        jPanelGrafica.setPreferredSize(new java.awt.Dimension(1200, 510));
        jPanelGrafica.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jPanelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanelGrafica.remove(contenedor);
        agregarGrafica(Integer.parseInt(SpinBoxAnnio.getValue().toString()));
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLannioGrafica;
    private javax.swing.JSpinner SpinBoxAnnio;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanelEntrada;
    private javax.swing.JPanel jPanelGrafica;
    // End of variables declaration//GEN-END:variables
}
