/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_sistema_sismico;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Allison
 */
public class PanelGrafica extends javax.swing.JPanel {

    /**
     * Creates new form PanelGrafica
     * Contiene paneles de las graficas
     */
    public PanelGrafica()  {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelTipo = new javax.swing.JPanel();
        try {
            panelTipo1 = new proyecto1_sistema_sismico.PanelTipo();
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        } catch (java.text.ParseException e2) {
            e2.printStackTrace();
        }
        jPanelMesEnAnnio = new javax.swing.JPanel();
        try {
            panelMesEnAnnio1 = new proyecto1_sistema_sismico.PanelMesEnAnnio();
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        } catch (java.text.ParseException e2) {
            e2.printStackTrace();
        }
        try {
            panelProvincia1 = new proyecto1_sistema_sismico.PanelProvincia();
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        } catch (java.text.ParseException e2) {
            e2.printStackTrace();
        }

        setBackground(new java.awt.Color(86, 86, 100));

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jPanelTipo.setBackground(new java.awt.Color(86, 86, 100));

        panelTipo1.setMaximumSize(new java.awt.Dimension(1500, 700));
        panelTipo1.setPreferredSize(new java.awt.Dimension(1300, 500));

        javax.swing.GroupLayout jPanelTipoLayout = new javax.swing.GroupLayout(jPanelTipo);
        jPanelTipo.setLayout(jPanelTipoLayout);
        jPanelTipoLayout.setHorizontalGroup(
            jPanelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(panelTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 1335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanelTipoLayout.setVerticalGroup(
            jPanelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(panelTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sismos Tipo de Origen", jPanelTipo);

        jPanelMesEnAnnio.setBackground(new java.awt.Color(86, 86, 100));

        javax.swing.GroupLayout jPanelMesEnAnnioLayout = new javax.swing.GroupLayout(jPanelMesEnAnnio);
        jPanelMesEnAnnio.setLayout(jPanelMesEnAnnioLayout);
        jPanelMesEnAnnioLayout.setHorizontalGroup(
            jPanelMesEnAnnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMesEnAnnioLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(panelMesEnAnnio1, javax.swing.GroupLayout.PREFERRED_SIZE, 1389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanelMesEnAnnioLayout.setVerticalGroup(
            jPanelMesEnAnnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMesEnAnnioLayout.createSequentialGroup()
                .addComponent(panelMesEnAnnio1, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 115, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sismos por Mes en un Año", jPanelMesEnAnnio);
        jTabbedPane1.addTab("Sismos por magnitud en Provincia", panelProvincia1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelMesEnAnnio;
    private javax.swing.JPanel jPanelTipo;
    private javax.swing.JTabbedPane jTabbedPane1;
    private proyecto1_sistema_sismico.PanelMesEnAnnio panelMesEnAnnio1;
    private proyecto1_sistema_sismico.PanelProvincia panelProvincia1;
    private proyecto1_sistema_sismico.PanelTipo panelTipo1;
    // End of variables declaration//GEN-END:variables

}
