/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_sistema_sismico;

/**
 *
 * @author Allison
 */
public class PanelGraficas extends javax.swing.JPanel {

    /**
     * Creates new form PanelGraficas
     */
    public PanelGraficas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        try {
            panelMesEnAnnio1 = new proyecto1_sistema_sismico.PanelMesEnAnnio();
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        } catch (java.text.ParseException e2) {
            e2.printStackTrace();
        }
        try {
            panelProvincia1 = new proyecto1_sistema_sismico.PanelProvincia();
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        } catch (java.text.ParseException e2) {
            e2.printStackTrace();
        }

        jTabbedPane1.addTab("tab1", panelMesEnAnnio1);
        jTabbedPane1.addTab("tab2", panelProvincia1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private proyecto1_sistema_sismico.PanelMesEnAnnio panelMesEnAnnio1;
    private proyecto1_sistema_sismico.PanelProvincia panelProvincia1;
    // End of variables declaration//GEN-END:variables
}
